### ISSUE TITLE
Error: Malformed UTF-8 data

### ISSUE THREAD

**Issue by Ningyoplug** [hq-af/twist-batch-downloader#2]
It used to work months ago when i used it to download several anime. But today I've tried to use it again and for some reason it's not working.

This is what it's been saying from the 2nd time i've tried to download this anime onwards:

```
C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1>twist-batch-downloader.exe carole-and-tuesday
> [1/1] Downloading 'carole-and-tuesday'
C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:10305
                        throw new Error('Malformed UTF-8 data');
                        ^

Error: Malformed UTF-8 data
    at Object.stringify (C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:10305:24)
    at Object.decryptURL (C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:120:30)
    at json.map.ep (C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:197:38)
    at Array.map (native)
    at Request.request.get [as _callback] (C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:197:22)
    at Request.self.callback (C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:32310:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1\twist-batch-downloader.exe:33282:10)
    at emitOne (events.js:115:13)

C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1>
```

The first time i tried to download this anime, this happened:

```
C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1>twist-batch-downloader.exe carole-and-tuesday
> [1/1] Downloading 'carole-and-tuesday'
  + Queued episodes : EP1 -> EP10
  - [1/10] Downloading EP1 : ''
  - [2/10] Downloading EP2 : ''
  - [3/10] Downloading EP3 : ''
  - [4/10] Downloading EP4 : ''
  - [5/10] Downloading EP5 : ''
  - [6/10] Downloading EP6 : ''
  - [7/10] Downloading EP7 : ''
  - [8/10] Downloading EP8 : ''
  - [9/10] Downloading EP9 : ''
  - [10/10] Downloading EP10 : ''
  √ Finished in 0.781s

√ All tasks completed in 0.797s

C:\Users\[MyName]\Desktop\twist-batch-downloader-0.0.1>twist-batch-downloader.exe carole-and-tuesday
```
obviously, it didn't actually download anything. it created the folder with the anime's name but inside the folder there was only a .MOE file named "twist.moe" and nothing else.
if i try to open it on my browser (Chrome) or with Notepad++, here's what's inside:

```
<html><title>You are being redirected...</title>
<noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
<script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='eD0nMG1TMicuc3Vic3RyKDMsIDEpICsgJycgKycnKyJkIi5zbGljZSgwLDEpICsgImVzdWN1ciIuY2hhckF0KDApKyJlbCIuY2hhckF0KDApICsgICcnICsgCiI4c3VjdXIiLmNoYXJBdCgwKSsnZCcgKyAgICcnICsnMmMnLnNsaWNlKDEsMikrJ2YnICsgICJiIiArICIiICsiNXN1Ii5zbGljZSgwLDEpICsgImJzdWN1ciIuY2hhckF0KDApKyIiICsndUc5Jy5jaGFyQXQoMikrJz0xJy5zbGljZSgxLDIpK1N0cmluZy5mcm9tQ2hhckNvZGUoMHgzMSkgKyAnNicgKyAgJ2YnICsgICAnJyArJzAnICsgICI4ayIuY2hhckF0KDApICsgICcnICsgCiJmdyIuY2hhckF0KDApICsgImMiICsgImMiICsgIiIgKycwJyArICBTdHJpbmcuZnJvbUNoYXJDb2RlKDB4MzYpICsgImQiLnNsaWNlKDAsMSkgKyAgJycgKyAKIjFzdWN1ciIuY2hhckF0KDApKyAnJyArJzEnICsgICIzbSIuY2hhckF0KDApICsgICcnICsgCiI1c3UiLnNsaWNlKDAsMSkgKyAiIiArU3RyaW5nLmZyb21DaGFyQ29kZSgweDY0KSArICdWeD5iJy5zdWJzdHIoMywgMSkgKyAnJyArImNzdWN1ciIuY2hhckF0KDApKyJiIiArICAnJyArJyc7ZG9jdW1lbnQuY29va2llPSdzc3VjdXJpJy5jaGFyQXQoMCkgKyAndXMnLmNoYXJBdCgwKSsnYycrJ3VzdScuY2hhckF0KDApICsnc3VjdXJyJy5jaGFyQXQoNSkgKyAnaScrJ19zdScuY2hhckF0KDApICsnc3VjdXJpYycuY2hhckF0KDYpKydsJy5jaGFyQXQoMCkrJ29zdWN1Jy5jaGFyQXQoMCkgICsnc3UnLmNoYXJBdCgxKSsnc3VjdXJkJy5jaGFyQXQoNSkgKyAncCcuY2hhckF0KDApKydyJysnJysnc3VjdXJpbycuY2hhckF0KDYpKyd4c3VjdScuY2hhckF0KDApICArJ3lzJy5jaGFyQXQoMCkrJ18nKyd1JysndScrJ2knKydkJysnX3N1Y3VyJy5jaGFyQXQoMCkrICcxJysnc3VjdXJjJy5jaGFyQXQoNSkgKyAnNScrJzVzJy5jaGFyQXQoMCkrJ2RzdWN1cmknLmNoYXJBdCgwKSArICdmJy5jaGFyQXQoMCkrJzRzdScuY2hhckF0KDApICsnMnN1YycuY2hhckF0KDApKyAnZXMnLmNoYXJBdCgwKSsiPSIgKyB4ICsgJztwYXRoPS87bWF4LWFnZT04NjQwMCc7IGxvY2F0aW9uLnJlbG9hZCgpOw==';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>
```

Hopefully this can help you fix the issue.

**Comment by hq-af** [comment]
should be fixed now, thanks for reporting
